-- MySQL Script generated by MySQL Workbench
-- Sun Apr 13 20:38:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IST270
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IST270` ;

-- -----------------------------------------------------
-- Schema IST270
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IST270` DEFAULT CHARACTER SET utf8 ;
USE `IST270` ;

-- -----------------------------------------------------
-- Table `IST270`.`call_leg_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`call_leg_types` ;

CREATE TABLE IF NOT EXISTS `IST270`.`call_leg_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `abbreviation` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`cdr_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`cdr_statistics` ;

CREATE TABLE IF NOT EXISTS `IST270`.`cdr_statistics` (
  `file_id` INT UNSIGNED NOT NULL,
  `ims_function` INT UNSIGNED NOT NULL,
  `fiveminuteepoch` DATETIME NOT NULL,
  `call_leg_id` INT NOT NULL,
  `disco_id` INT NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  `duration` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`file_id`),
  INDEX `ims_idx` (`ims_function` ASC) VISIBLE,
  INDEX `call_leg_idx` (`call_leg_id` ASC) VISIBLE,
  INDEX `disco_idx` (`disco_id` ASC) VISIBLE,
  CONSTRAINT `ims_func`
    FOREIGN KEY (`ims_function`)
    REFERENCES `IST270`.`ims_functions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `call_leg`
    FOREIGN KEY (`call_leg_id`)
    REFERENCES `IST270`.`call_leg_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disco`
    FOREIGN KEY (`disco_id`)
    REFERENCES `IST270`.`disconnect_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`diameter_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`diameter_messages` ;

CREATE TABLE IF NOT EXISTS `IST270`.`diameter_messages` (
  `diameter_id` INT UNSIGNED NOT NULL,
  `cdr_data` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`diameter_id`),
  CONSTRAINT `diameter`
    FOREIGN KEY (`diameter_id`)
    REFERENCES `IST270`.`diameter_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`diameter_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`diameter_types` ;

CREATE TABLE IF NOT EXISTS `IST270`.`diameter_types` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'Known types are \nipv4, carrier_name, mta, route label\n\nunknown number of types',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`disconnect_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`disconnect_codes` ;

CREATE TABLE IF NOT EXISTS `IST270`.`disconnect_codes` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`files_cdr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`files_cdr` ;

CREATE TABLE IF NOT EXISTS `IST270`.`files_cdr` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `filename` VARCHAR(1024) NOT NULL,
  `ims_function` INT UNSIGNED NOT NULL,
  `ccf_node` INT NOT NULL,
  `file_create_time` DATETIME NOT NULL,
  `file_delivery_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ims_idx` (`ims_function` ASC) VISIBLE,
  INDEX `node_idx` (`ccf_node` ASC) VISIBLE,
  CONSTRAINT `ims`
    FOREIGN KEY (`ims_function`)
    REFERENCES `IST270`.`ims_functions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `node`
    FOREIGN KEY (`ccf_node`)
    REFERENCES `IST270`.`nodes_ccf` (`id_node`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`ims_functions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`ims_functions` ;

CREATE TABLE IF NOT EXISTS `IST270`.`ims_functions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `filename_key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`nodes_ccf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`nodes_ccf` ;

CREATE TABLE IF NOT EXISTS `IST270`.`nodes_ccf` (
  `id_node` INT NOT NULL AUTO_INCREMENT,
  `node_fqdn` VARCHAR(255) NOT NULL DEFAULT 'unknown' COMMENT 'contains FQDN of serving node\n',
  `filename_key` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_node`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IST270`.`reason_header`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IST270`.`reason_header` ;

CREATE TABLE IF NOT EXISTS `IST270`.`reason_header` (
  `id` INT NOT NULL,
  `ims_function_id` INT UNSIGNED NOT NULL,
  `call_leg_id` INT NOT NULL,
  `cdr_data` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ims_idx` (`ims_function_id` ASC) VISIBLE,
  INDEX `leg_idx` (`call_leg_id` ASC) VISIBLE,
  CONSTRAINT `ims`
    FOREIGN KEY (`ims_function_id`)
    REFERENCES `IST270`.`ims_functions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `leg`
    FOREIGN KEY (`call_leg_id`)
    REFERENCES `IST270`.`call_leg_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
